spring.application.name=InforSystemBackend

# DataBase
spring.datasource.url=jdbc:mysql://localhost:3306/inforsys
spring.datasource.username=root
spring.datasource.password=xinchengyun7
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# lazy
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true


# Swagger API and Swagger UI Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Server port
server.port=8088

# Devtools setting
spring.devtools.restart.enabled=false

# Logging
logging.level.org.springframework=INFO
## production
#logging.level.org.springframework=INFO


# Static resources configuration
spring.mvc.static-path-pattern=/static/**

# date
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.time-zone=UTC